/**
* Makes E2E Coverage report for CodeCov
* Consumes E2E report generated by playwright e2e tests
* Coverts it into a coverage format compatible with CodeCov
* Author: Mandar Devarshi
* Year: 2022
*/

// Import Playwright Test Results
import results from './results.json' assert {type: 'json'}
// Import Json Editor
// https://www.npmjs.com/package/edit-json-file
import editJsonFile from "edit-json-file";

// Open result file which will hold coverage result in the end
let file = editJsonFile(`./coverage/result.json`)
// Empty results file
file.empty()

// Playwright tests result object i.e target of conversion
// TODO: Needs improvement
const convertObj = results.suites[0].specs

// Object to store final report object
var coverageReport = {}

// Passed or Failed
for (const [key,value] of Object.entries(convertObj)) {
    // Stores results of test parts
    var tempObj = {}
    if(!value.ok){
        // Test Failed
        // Add to coverage report
        tempObj = addendumToCoverageReportFailedTest(value, value.line, value.column)
    }else{
        // Test Passed
        // Add to coverage report
        tempObj = addendumToCoverageReportPassedTest(value, value.line, value.column)
    }
    // Create A JSON file for coverage
    Object.assign(coverageReport,{...tempObj})
}

createCoverageReport(coverageReport)

// Save to disk e2e coverage JSON results
function createCoverageReport(coverageReport){
    file.set(coverageReport)
    file.save()
    return
}

function addendumToCoverageReportPassedTest(result, line, column) {
    // create the e2e object
    var coverageReportObj = {}
    const testRoot = result.title
    const path = result.file.toString()
    // Loop over length
    for (let index = result.tests.length-1; index >=0 ;index--){
        const statementMap = {
            [index]:{
                "start":{
                    "line": line,
                    "column": column
                },
                "end":{
                    "line": line,
                    "column": column
                }
            }
        }
        const fnMap={}
        const branchMap={}
        const s = {
            [index]: 1
        }
        const f={}
        const b={}

        coverageReportObj = {
            [testRoot]:{
                path: path,
                statementMap: statementMap,
                fnMap : fnMap,
                branchMap: branchMap,
                s:s,
                f:f,
                b:b
            }
        }
    }
    return coverageReportObj
}

function addendumToCoverageReportFailedTest(result, line, column){
    var coverageReportObj = {}
    const testRoot = result.title
    const path = result.file.toString()
    // Loop over length
    for (let index = result.tests.length-1; index >=0 ;index--){
        const statementMap = {
            [index]:{
                "start":{
                    "line": line,
                    "column": column
                },
                "end":{
                    "line": line,
                    "column": column
                }
            }
        }
        const fnMap={}
        const branchMap={}
        const s = {
            [index]: 0
        }
        const f={}
        const b={}

        coverageReportObj = {
            [testRoot]:{
                path: path,
                statementMap: statementMap,
                fnMap : fnMap,
                branchMap: branchMap,
                s:s,
                f:f,
                b:b
            }
        }
    }
    return coverageReportObj
}